/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSessionPulseRouteImport } from './routes/api/session-pulse'
import { Route as ApiRefugioRouteImport } from './routes/api/refugio'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPrivateMessagesRouteImport } from './routes/api/private-messages'
import { Route as ApiPresenceRouteImport } from './routes/api/presence'
import { Route as ApiMesasRouteImport } from './routes/api/mesas'
import { Route as ApiInviteRouteImport } from './routes/api/invite'
import { Route as ApiGenerateInfograficoRouteImport } from './routes/api/generate-infografico'
import { Route as ApiGalleryRouteImport } from './routes/api/gallery'
import { Route as ApiContinuityMapsRouteImport } from './routes/api/continuity-maps'
import { Route as ApiCommunityChatRouteImport } from './routes/api/community-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCharactersRouteImport } from './routes/api/characters'
import { Route as ApiCampaignContinuityRouteImport } from './routes/api/campaign-continuity'
import { Route as AuthenticatedStateRouteImport } from './routes/_authenticated/state'
import { Route as AuthenticatedRevisaoRouteImport } from './routes/_authenticated/revisao'
import { Route as AuthenticatedRegistroVivoRouteImport } from './routes/_authenticated/registro-vivo'
import { Route as AuthenticatedRefugioRouteImport } from './routes/_authenticated/refugio'
import { Route as AuthenticatedPersonagensRouteImport } from './routes/_authenticated/personagens'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMicroappRouteImport } from './routes/_authenticated/microapp'
import { Route as AuthenticatedMestreRouteImport } from './routes/_authenticated/mestre'
import { Route as AuthenticatedMapasRouteImport } from './routes/_authenticated/mapas'
import { Route as AuthenticatedKallistisPresenteRouteImport } from './routes/_authenticated/kallistis-presente'
import { Route as AuthenticatedJardimRouteImport } from './routes/_authenticated/jardim'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiVttPlayerPhraseRouteImport } from './routes/api/vtt/player-phrase'
import { Route as ApiVttHandoffRouteImport } from './routes/api/vtt/handoff'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiProfileAvatarRouteImport } from './routes/api/profile.avatar'
import { Route as ApiMasterStateRouteImport } from './routes/api/master/state'
import { Route as ApiMasterPrivateMessagesRouteImport } from './routes/api/master/private-messages'
import { Route as ApiMasterPresenceRouteImport } from './routes/api/master/presence'
import { Route as ApiMasterLiveSessionRouteImport } from './routes/api/master/live-session'
import { Route as ApiMasterCommunityChatRouteImport } from './routes/api/master/community-chat'
import { Route as ApiMasterCharactersRouteImport } from './routes/api/master/characters'
import { Route as ApiMasterBridgeRouteImport } from './routes/api/master/bridge'
import { Route as ApiGalleryFileRouteImport } from './routes/api/gallery.file'
import { Route as ApiContinuityMapsDocumentsRouteImport } from './routes/api/continuity-maps.documents'
import { Route as ApiContinuityMapsMapIdRouteImport } from './routes/api/continuity-maps.$mapId'
import { Route as ApiChatThreadRouteImport } from './routes/api/chat/thread'
import { Route as ApiChatMutationsRouteImport } from './routes/api/chat/mutations'
import { Route as ApiChatCampaignsRouteImport } from './routes/api/chat/campaigns'
import { Route as ApiChannelsTelegramDialogueRouteImport } from './routes/api/channels/telegram-dialogue'
import { Route as ApiChannelsTelegramRouteImport } from './routes/api/channels/telegram'
import { Route as ApiBridgeOlharDeKairosRouteImport } from './routes/api/bridge/olhar-de-kairos'
import { Route as ApiBridgeDecifrarSnapshotLocalRouteImport } from './routes/api/bridge/decifrar-snapshot-local'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthRecoveryCodeRouteImport } from './routes/api/auth/recovery-code'
import { Route as ApiAuthGooglePlayerOnboardingRouteImport } from './routes/api/auth/google-player-onboarding'
import { Route as ApiAdminTalBootstrapRouteImport } from './routes/api/admin/tal-bootstrap'
import { Route as ApiAdminRecoveryCodeRouteImport } from './routes/api/admin/recovery-code'
import { Route as ApiAdminPlayerAccessStatusRouteImport } from './routes/api/admin/player-access-status'
import { Route as ApiAdminMesasRouteImport } from './routes/api/admin/mesas'
import { Route as ApiAdminMesaResponsibleMasterRouteImport } from './routes/api/admin/mesa-responsible-master'
import { Route as ApiAdminMesaMembershipsRouteImport } from './routes/api/admin/mesa-memberships'
import { Route as ApiAdminInvitesRouteImport } from './routes/api/admin/invites'
import { Route as ApiAdminCharacterMesasRouteImport } from './routes/api/admin/character-mesas'
import { Route as ApiAdminAppAccessRouteImport } from './routes/api/admin/app-access'
import { Route as AuthenticatedTrilhaThreadIdRouteImport } from './routes/_authenticated/trilha.$threadId'
import { Route as AuthenticatedSurfaceSurfaceRouteImport } from './routes/_authenticated/surface.$surface'
import { Route as AuthenticatedMapaContinuidadeMapIdRouteImport } from './routes/_authenticated/mapa-continuidade.$mapId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedCampanhaMesaSlugRouteImport } from './routes/_authenticated/campanha.$mesaSlug'
import { Route as ApiMasterSurfaceSurfaceRouteImport } from './routes/api/master/surface.$surface'
import { Route as AuthenticatedPersonagemCharacterIdFichaRouteImport } from './routes/_authenticated/personagem/$characterId/ficha'
import { Route as ApiInternalVttHandoffConsumeRouteImport } from './routes/api/internal/vtt/handoff/consume'
import { Route as ApiInternalVttCharactersReadRouteImport } from './routes/api/internal/vtt/characters/read'

const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionPulseRoute = ApiSessionPulseRouteImport.update({
  id: '/api/session-pulse',
  path: '/api/session-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefugioRoute = ApiRefugioRouteImport.update({
  id: '/api/refugio',
  path: '/api/refugio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateMessagesRoute = ApiPrivateMessagesRouteImport.update({
  id: '/api/private-messages',
  path: '/api/private-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresenceRoute = ApiPresenceRouteImport.update({
  id: '/api/presence',
  path: '/api/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMesasRoute = ApiMesasRouteImport.update({
  id: '/api/mesas',
  path: '/api/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteRoute = ApiInviteRouteImport.update({
  id: '/api/invite',
  path: '/api/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateInfograficoRoute = ApiGenerateInfograficoRouteImport.update({
  id: '/api/generate-infografico',
  path: '/api/generate-infografico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryRoute = ApiGalleryRouteImport.update({
  id: '/api/gallery',
  path: '/api/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContinuityMapsRoute = ApiContinuityMapsRouteImport.update({
  id: '/api/continuity-maps',
  path: '/api/continuity-maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityChatRoute = ApiCommunityChatRouteImport.update({
  id: '/api/community-chat',
  path: '/api/community-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersRoute = ApiCharactersRouteImport.update({
  id: '/api/characters',
  path: '/api/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignContinuityRoute = ApiCampaignContinuityRouteImport.update({
  id: '/api/campaign-continuity',
  path: '/api/campaign-continuity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStateRoute = AuthenticatedStateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisaoRoute = AuthenticatedRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroVivoRoute =
  AuthenticatedRegistroVivoRouteImport.update({
    id: '/registro-vivo',
    path: '/registro-vivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefugioRoute = AuthenticatedRefugioRouteImport.update({
  id: '/refugio',
  path: '/refugio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonagensRoute =
  AuthenticatedPersonagensRouteImport.update({
    id: '/personagens',
    path: '/personagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMicroappRoute = AuthenticatedMicroappRouteImport.update({
  id: '/microapp',
  path: '/microapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMestreRoute = AuthenticatedMestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapasRoute = AuthenticatedMapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKallistisPresenteRoute =
  AuthenticatedKallistisPresenteRouteImport.update({
    id: '/kallistis-presente',
    path: '/kallistis-presente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJardimRoute = AuthenticatedJardimRouteImport.update({
  id: '/jardim',
  path: '/jardim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVttPlayerPhraseRoute = ApiVttPlayerPhraseRouteImport.update({
  id: '/api/vtt/player-phrase',
  path: '/api/vtt/player-phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVttHandoffRoute = ApiVttHandoffRouteImport.update({
  id: '/api/vtt/handoff',
  path: '/api/vtt/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarRoute = ApiProfileAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ApiProfileRoute,
} as any)
const ApiMasterStateRoute = ApiMasterStateRouteImport.update({
  id: '/api/master/state',
  path: '/api/master/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterPrivateMessagesRoute =
  ApiMasterPrivateMessagesRouteImport.update({
    id: '/api/master/private-messages',
    path: '/api/master/private-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMasterPresenceRoute = ApiMasterPresenceRouteImport.update({
  id: '/api/master/presence',
  path: '/api/master/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterLiveSessionRoute = ApiMasterLiveSessionRouteImport.update({
  id: '/api/master/live-session',
  path: '/api/master/live-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterCommunityChatRoute = ApiMasterCommunityChatRouteImport.update({
  id: '/api/master/community-chat',
  path: '/api/master/community-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterCharactersRoute = ApiMasterCharactersRouteImport.update({
  id: '/api/master/characters',
  path: '/api/master/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterBridgeRoute = ApiMasterBridgeRouteImport.update({
  id: '/api/master/bridge',
  path: '/api/master/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryFileRoute = ApiGalleryFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiGalleryRoute,
} as any)
const ApiContinuityMapsDocumentsRoute =
  ApiContinuityMapsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiContinuityMapsRoute,
  } as any)
const ApiContinuityMapsMapIdRoute = ApiContinuityMapsMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => ApiContinuityMapsRoute,
} as any)
const ApiChatThreadRoute = ApiChatThreadRouteImport.update({
  id: '/thread',
  path: '/thread',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatMutationsRoute = ApiChatMutationsRouteImport.update({
  id: '/mutations',
  path: '/mutations',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatCampaignsRoute = ApiChatCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChannelsTelegramDialogueRoute =
  ApiChannelsTelegramDialogueRouteImport.update({
    id: '/api/channels/telegram-dialogue',
    path: '/api/channels/telegram-dialogue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChannelsTelegramRoute = ApiChannelsTelegramRouteImport.update({
  id: '/api/channels/telegram',
  path: '/api/channels/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeOlharDeKairosRoute = ApiBridgeOlharDeKairosRouteImport.update({
  id: '/api/bridge/olhar-de-kairos',
  path: '/api/bridge/olhar-de-kairos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeDecifrarSnapshotLocalRoute =
  ApiBridgeDecifrarSnapshotLocalRouteImport.update({
    id: '/api/bridge/decifrar-snapshot-local',
    path: '/api/bridge/decifrar-snapshot-local',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryCodeRoute = ApiAuthRecoveryCodeRouteImport.update({
  id: '/api/auth/recovery-code',
  path: '/api/auth/recovery-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGooglePlayerOnboardingRoute =
  ApiAuthGooglePlayerOnboardingRouteImport.update({
    id: '/api/auth/google-player-onboarding',
    path: '/api/auth/google-player-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTalBootstrapRoute = ApiAdminTalBootstrapRouteImport.update({
  id: '/api/admin/tal-bootstrap',
  path: '/api/admin/tal-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRecoveryCodeRoute = ApiAdminRecoveryCodeRouteImport.update({
  id: '/api/admin/recovery-code',
  path: '/api/admin/recovery-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlayerAccessStatusRoute =
  ApiAdminPlayerAccessStatusRouteImport.update({
    id: '/api/admin/player-access-status',
    path: '/api/admin/player-access-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMesasRoute = ApiAdminMesasRouteImport.update({
  id: '/api/admin/mesas',
  path: '/api/admin/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMesaResponsibleMasterRoute =
  ApiAdminMesaResponsibleMasterRouteImport.update({
    id: '/api/admin/mesa-responsible-master',
    path: '/api/admin/mesa-responsible-master',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMesaMembershipsRoute = ApiAdminMesaMembershipsRouteImport.update({
  id: '/api/admin/mesa-memberships',
  path: '/api/admin/mesa-memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitesRoute = ApiAdminInvitesRouteImport.update({
  id: '/api/admin/invites',
  path: '/api/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCharacterMesasRoute = ApiAdminCharacterMesasRouteImport.update({
  id: '/api/admin/character-mesas',
  path: '/api/admin/character-mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAppAccessRoute = ApiAdminAppAccessRouteImport.update({
  id: '/api/admin/app-access',
  path: '/api/admin/app-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhaThreadIdRoute =
  AuthenticatedTrilhaThreadIdRouteImport.update({
    id: '/trilha/$threadId',
    path: '/trilha/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSurfaceSurfaceRoute =
  AuthenticatedSurfaceSurfaceRouteImport.update({
    id: '/surface/$surface',
    path: '/surface/$surface',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapaContinuidadeMapIdRoute =
  AuthenticatedMapaContinuidadeMapIdRouteImport.update({
    id: '/mapa-continuidade/$mapId',
    path: '/mapa-continuidade/$mapId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampanhaMesaSlugRoute =
  AuthenticatedCampanhaMesaSlugRouteImport.update({
    id: '/campanha/$mesaSlug',
    path: '/campanha/$mesaSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiMasterSurfaceSurfaceRoute = ApiMasterSurfaceSurfaceRouteImport.update({
  id: '/api/master/surface/$surface',
  path: '/api/master/surface/$surface',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPersonagemCharacterIdFichaRoute =
  AuthenticatedPersonagemCharacterIdFichaRouteImport.update({
    id: '/personagem/$characterId/ficha',
    path: '/personagem/$characterId/ficha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiInternalVttHandoffConsumeRoute =
  ApiInternalVttHandoffConsumeRouteImport.update({
    id: '/api/internal/vtt/handoff/consume',
    path: '/api/internal/vtt/handoff/consume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalVttCharactersReadRoute =
  ApiInternalVttCharactersReadRouteImport.update({
    id: '/api/internal/vtt/characters/read',
    path: '/api/internal/vtt/characters/read',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jardim': typeof AuthenticatedJardimRoute
  '/kallistis-presente': typeof AuthenticatedKallistisPresenteRoute
  '/mapas': typeof AuthenticatedMapasRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/microapp': typeof AuthenticatedMicroappRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/personagens': typeof AuthenticatedPersonagensRoute
  '/refugio': typeof AuthenticatedRefugioRoute
  '/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/state': typeof AuthenticatedStateRoute
  '/api/campaign-continuity': typeof ApiCampaignContinuityRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/community-chat': typeof ApiCommunityChatRoute
  '/api/continuity-maps': typeof ApiContinuityMapsRouteWithChildren
  '/api/gallery': typeof ApiGalleryRouteWithChildren
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/mesas': typeof ApiMesasRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/private-messages': typeof ApiPrivateMessagesRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/refugio': typeof ApiRefugioRoute
  '/api/session-pulse': typeof ApiSessionPulseRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/campanha/$mesaSlug': typeof AuthenticatedCampanhaMesaSlugRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/mapa-continuidade/$mapId': typeof AuthenticatedMapaContinuidadeMapIdRoute
  '/surface/$surface': typeof AuthenticatedSurfaceSurfaceRoute
  '/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/admin/app-access': typeof ApiAdminAppAccessRoute
  '/api/admin/character-mesas': typeof ApiAdminCharacterMesasRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/mesa-memberships': typeof ApiAdminMesaMembershipsRoute
  '/api/admin/mesa-responsible-master': typeof ApiAdminMesaResponsibleMasterRoute
  '/api/admin/mesas': typeof ApiAdminMesasRoute
  '/api/admin/player-access-status': typeof ApiAdminPlayerAccessStatusRoute
  '/api/admin/recovery-code': typeof ApiAdminRecoveryCodeRoute
  '/api/admin/tal-bootstrap': typeof ApiAdminTalBootstrapRoute
  '/api/auth/google-player-onboarding': typeof ApiAuthGooglePlayerOnboardingRoute
  '/api/auth/recovery-code': typeof ApiAuthRecoveryCodeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bridge/decifrar-snapshot-local': typeof ApiBridgeDecifrarSnapshotLocalRoute
  '/api/bridge/olhar-de-kairos': typeof ApiBridgeOlharDeKairosRoute
  '/api/channels/telegram': typeof ApiChannelsTelegramRoute
  '/api/channels/telegram-dialogue': typeof ApiChannelsTelegramDialogueRoute
  '/api/chat/campaigns': typeof ApiChatCampaignsRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/continuity-maps/$mapId': typeof ApiContinuityMapsMapIdRoute
  '/api/continuity-maps/documents': typeof ApiContinuityMapsDocumentsRoute
  '/api/gallery/file': typeof ApiGalleryFileRoute
  '/api/master/bridge': typeof ApiMasterBridgeRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
  '/api/master/community-chat': typeof ApiMasterCommunityChatRoute
  '/api/master/live-session': typeof ApiMasterLiveSessionRoute
  '/api/master/presence': typeof ApiMasterPresenceRoute
  '/api/master/private-messages': typeof ApiMasterPrivateMessagesRoute
  '/api/master/state': typeof ApiMasterStateRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/vtt/handoff': typeof ApiVttHandoffRoute
  '/api/vtt/player-phrase': typeof ApiVttPlayerPhraseRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/personagem/$characterId/ficha': typeof AuthenticatedPersonagemCharacterIdFichaRoute
  '/api/master/surface/$surface': typeof ApiMasterSurfaceSurfaceRoute
  '/api/internal/vtt/characters/read': typeof ApiInternalVttCharactersReadRoute
  '/api/internal/vtt/handoff/consume': typeof ApiInternalVttHandoffConsumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jardim': typeof AuthenticatedJardimRoute
  '/kallistis-presente': typeof AuthenticatedKallistisPresenteRoute
  '/mapas': typeof AuthenticatedMapasRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/microapp': typeof AuthenticatedMicroappRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/personagens': typeof AuthenticatedPersonagensRoute
  '/refugio': typeof AuthenticatedRefugioRoute
  '/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/state': typeof AuthenticatedStateRoute
  '/api/campaign-continuity': typeof ApiCampaignContinuityRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/community-chat': typeof ApiCommunityChatRoute
  '/api/continuity-maps': typeof ApiContinuityMapsRouteWithChildren
  '/api/gallery': typeof ApiGalleryRouteWithChildren
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/mesas': typeof ApiMesasRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/private-messages': typeof ApiPrivateMessagesRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/refugio': typeof ApiRefugioRoute
  '/api/session-pulse': typeof ApiSessionPulseRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/campanha/$mesaSlug': typeof AuthenticatedCampanhaMesaSlugRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/mapa-continuidade/$mapId': typeof AuthenticatedMapaContinuidadeMapIdRoute
  '/surface/$surface': typeof AuthenticatedSurfaceSurfaceRoute
  '/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/admin/app-access': typeof ApiAdminAppAccessRoute
  '/api/admin/character-mesas': typeof ApiAdminCharacterMesasRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/mesa-memberships': typeof ApiAdminMesaMembershipsRoute
  '/api/admin/mesa-responsible-master': typeof ApiAdminMesaResponsibleMasterRoute
  '/api/admin/mesas': typeof ApiAdminMesasRoute
  '/api/admin/player-access-status': typeof ApiAdminPlayerAccessStatusRoute
  '/api/admin/recovery-code': typeof ApiAdminRecoveryCodeRoute
  '/api/admin/tal-bootstrap': typeof ApiAdminTalBootstrapRoute
  '/api/auth/google-player-onboarding': typeof ApiAuthGooglePlayerOnboardingRoute
  '/api/auth/recovery-code': typeof ApiAuthRecoveryCodeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bridge/decifrar-snapshot-local': typeof ApiBridgeDecifrarSnapshotLocalRoute
  '/api/bridge/olhar-de-kairos': typeof ApiBridgeOlharDeKairosRoute
  '/api/channels/telegram': typeof ApiChannelsTelegramRoute
  '/api/channels/telegram-dialogue': typeof ApiChannelsTelegramDialogueRoute
  '/api/chat/campaigns': typeof ApiChatCampaignsRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/continuity-maps/$mapId': typeof ApiContinuityMapsMapIdRoute
  '/api/continuity-maps/documents': typeof ApiContinuityMapsDocumentsRoute
  '/api/gallery/file': typeof ApiGalleryFileRoute
  '/api/master/bridge': typeof ApiMasterBridgeRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
  '/api/master/community-chat': typeof ApiMasterCommunityChatRoute
  '/api/master/live-session': typeof ApiMasterLiveSessionRoute
  '/api/master/presence': typeof ApiMasterPresenceRoute
  '/api/master/private-messages': typeof ApiMasterPrivateMessagesRoute
  '/api/master/state': typeof ApiMasterStateRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/vtt/handoff': typeof ApiVttHandoffRoute
  '/api/vtt/player-phrase': typeof ApiVttPlayerPhraseRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/personagem/$characterId/ficha': typeof AuthenticatedPersonagemCharacterIdFichaRoute
  '/api/master/surface/$surface': typeof ApiMasterSurfaceSurfaceRoute
  '/api/internal/vtt/characters/read': typeof ApiInternalVttCharactersReadRoute
  '/api/internal/vtt/handoff/consume': typeof ApiInternalVttHandoffConsumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/convite': typeof ConviteRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/jardim': typeof AuthenticatedJardimRoute
  '/_authenticated/kallistis-presente': typeof AuthenticatedKallistisPresenteRoute
  '/_authenticated/mapas': typeof AuthenticatedMapasRoute
  '/_authenticated/mestre': typeof AuthenticatedMestreRoute
  '/_authenticated/microapp': typeof AuthenticatedMicroappRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/personagens': typeof AuthenticatedPersonagensRoute
  '/_authenticated/refugio': typeof AuthenticatedRefugioRoute
  '/_authenticated/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/_authenticated/revisao': typeof AuthenticatedRevisaoRoute
  '/_authenticated/state': typeof AuthenticatedStateRoute
  '/api/campaign-continuity': typeof ApiCampaignContinuityRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/community-chat': typeof ApiCommunityChatRoute
  '/api/continuity-maps': typeof ApiContinuityMapsRouteWithChildren
  '/api/gallery': typeof ApiGalleryRouteWithChildren
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/invite': typeof ApiInviteRoute
  '/api/mesas': typeof ApiMesasRoute
  '/api/presence': typeof ApiPresenceRoute
  '/api/private-messages': typeof ApiPrivateMessagesRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/refugio': typeof ApiRefugioRoute
  '/api/session-pulse': typeof ApiSessionPulseRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/campanha/$mesaSlug': typeof AuthenticatedCampanhaMesaSlugRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/mapa-continuidade/$mapId': typeof AuthenticatedMapaContinuidadeMapIdRoute
  '/_authenticated/surface/$surface': typeof AuthenticatedSurfaceSurfaceRoute
  '/_authenticated/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/admin/app-access': typeof ApiAdminAppAccessRoute
  '/api/admin/character-mesas': typeof ApiAdminCharacterMesasRoute
  '/api/admin/invites': typeof ApiAdminInvitesRoute
  '/api/admin/mesa-memberships': typeof ApiAdminMesaMembershipsRoute
  '/api/admin/mesa-responsible-master': typeof ApiAdminMesaResponsibleMasterRoute
  '/api/admin/mesas': typeof ApiAdminMesasRoute
  '/api/admin/player-access-status': typeof ApiAdminPlayerAccessStatusRoute
  '/api/admin/recovery-code': typeof ApiAdminRecoveryCodeRoute
  '/api/admin/tal-bootstrap': typeof ApiAdminTalBootstrapRoute
  '/api/auth/google-player-onboarding': typeof ApiAuthGooglePlayerOnboardingRoute
  '/api/auth/recovery-code': typeof ApiAuthRecoveryCodeRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/bridge/decifrar-snapshot-local': typeof ApiBridgeDecifrarSnapshotLocalRoute
  '/api/bridge/olhar-de-kairos': typeof ApiBridgeOlharDeKairosRoute
  '/api/channels/telegram': typeof ApiChannelsTelegramRoute
  '/api/channels/telegram-dialogue': typeof ApiChannelsTelegramDialogueRoute
  '/api/chat/campaigns': typeof ApiChatCampaignsRoute
  '/api/chat/mutations': typeof ApiChatMutationsRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/continuity-maps/$mapId': typeof ApiContinuityMapsMapIdRoute
  '/api/continuity-maps/documents': typeof ApiContinuityMapsDocumentsRoute
  '/api/gallery/file': typeof ApiGalleryFileRoute
  '/api/master/bridge': typeof ApiMasterBridgeRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
  '/api/master/community-chat': typeof ApiMasterCommunityChatRoute
  '/api/master/live-session': typeof ApiMasterLiveSessionRoute
  '/api/master/presence': typeof ApiMasterPresenceRoute
  '/api/master/private-messages': typeof ApiMasterPrivateMessagesRoute
  '/api/master/state': typeof ApiMasterStateRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/vtt/handoff': typeof ApiVttHandoffRoute
  '/api/vtt/player-phrase': typeof ApiVttPlayerPhraseRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/personagem/$characterId/ficha': typeof AuthenticatedPersonagemCharacterIdFichaRoute
  '/api/master/surface/$surface': typeof ApiMasterSurfaceSurfaceRoute
  '/api/internal/vtt/characters/read': typeof ApiInternalVttCharactersReadRoute
  '/api/internal/vtt/handoff/consume': typeof ApiInternalVttHandoffConsumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/convite'
    | '/agenda'
    | '/galeria'
    | '/home'
    | '/jardim'
    | '/kallistis-presente'
    | '/mapas'
    | '/mestre'
    | '/microapp'
    | '/perfil'
    | '/perfis'
    | '/personagens'
    | '/refugio'
    | '/registro-vivo'
    | '/revisao'
    | '/state'
    | '/api/campaign-continuity'
    | '/api/characters'
    | '/api/chat'
    | '/api/community-chat'
    | '/api/continuity-maps'
    | '/api/gallery'
    | '/api/generate-infografico'
    | '/api/invite'
    | '/api/mesas'
    | '/api/presence'
    | '/api/private-messages'
    | '/api/profile'
    | '/api/refugio'
    | '/api/session-pulse'
    | '/api/transcribe'
    | '/api/tts'
    | '/campanha/$mesaSlug'
    | '/chat/$threadId'
    | '/mapa-continuidade/$mapId'
    | '/surface/$surface'
    | '/trilha/$threadId'
    | '/api/admin/app-access'
    | '/api/admin/character-mesas'
    | '/api/admin/invites'
    | '/api/admin/mesa-memberships'
    | '/api/admin/mesa-responsible-master'
    | '/api/admin/mesas'
    | '/api/admin/player-access-status'
    | '/api/admin/recovery-code'
    | '/api/admin/tal-bootstrap'
    | '/api/auth/google-player-onboarding'
    | '/api/auth/recovery-code'
    | '/api/auth/session'
    | '/api/bridge/decifrar-snapshot-local'
    | '/api/bridge/olhar-de-kairos'
    | '/api/channels/telegram'
    | '/api/channels/telegram-dialogue'
    | '/api/chat/campaigns'
    | '/api/chat/mutations'
    | '/api/chat/thread'
    | '/api/continuity-maps/$mapId'
    | '/api/continuity-maps/documents'
    | '/api/gallery/file'
    | '/api/master/bridge'
    | '/api/master/characters'
    | '/api/master/community-chat'
    | '/api/master/live-session'
    | '/api/master/presence'
    | '/api/master/private-messages'
    | '/api/master/state'
    | '/api/profile/avatar'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/vtt/handoff'
    | '/api/vtt/player-phrase'
    | '/chat/'
    | '/personagem/$characterId/ficha'
    | '/api/master/surface/$surface'
    | '/api/internal/vtt/characters/read'
    | '/api/internal/vtt/handoff/consume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/convite'
    | '/agenda'
    | '/galeria'
    | '/home'
    | '/jardim'
    | '/kallistis-presente'
    | '/mapas'
    | '/mestre'
    | '/microapp'
    | '/perfil'
    | '/perfis'
    | '/personagens'
    | '/refugio'
    | '/registro-vivo'
    | '/revisao'
    | '/state'
    | '/api/campaign-continuity'
    | '/api/characters'
    | '/api/chat'
    | '/api/community-chat'
    | '/api/continuity-maps'
    | '/api/gallery'
    | '/api/generate-infografico'
    | '/api/invite'
    | '/api/mesas'
    | '/api/presence'
    | '/api/private-messages'
    | '/api/profile'
    | '/api/refugio'
    | '/api/session-pulse'
    | '/api/transcribe'
    | '/api/tts'
    | '/campanha/$mesaSlug'
    | '/chat/$threadId'
    | '/mapa-continuidade/$mapId'
    | '/surface/$surface'
    | '/trilha/$threadId'
    | '/api/admin/app-access'
    | '/api/admin/character-mesas'
    | '/api/admin/invites'
    | '/api/admin/mesa-memberships'
    | '/api/admin/mesa-responsible-master'
    | '/api/admin/mesas'
    | '/api/admin/player-access-status'
    | '/api/admin/recovery-code'
    | '/api/admin/tal-bootstrap'
    | '/api/auth/google-player-onboarding'
    | '/api/auth/recovery-code'
    | '/api/auth/session'
    | '/api/bridge/decifrar-snapshot-local'
    | '/api/bridge/olhar-de-kairos'
    | '/api/channels/telegram'
    | '/api/channels/telegram-dialogue'
    | '/api/chat/campaigns'
    | '/api/chat/mutations'
    | '/api/chat/thread'
    | '/api/continuity-maps/$mapId'
    | '/api/continuity-maps/documents'
    | '/api/gallery/file'
    | '/api/master/bridge'
    | '/api/master/characters'
    | '/api/master/community-chat'
    | '/api/master/live-session'
    | '/api/master/presence'
    | '/api/master/private-messages'
    | '/api/master/state'
    | '/api/profile/avatar'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/vtt/handoff'
    | '/api/vtt/player-phrase'
    | '/chat'
    | '/personagem/$characterId/ficha'
    | '/api/master/surface/$surface'
    | '/api/internal/vtt/characters/read'
    | '/api/internal/vtt/handoff/consume'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/convite'
    | '/_authenticated/agenda'
    | '/_authenticated/galeria'
    | '/_authenticated/home'
    | '/_authenticated/jardim'
    | '/_authenticated/kallistis-presente'
    | '/_authenticated/mapas'
    | '/_authenticated/mestre'
    | '/_authenticated/microapp'
    | '/_authenticated/perfil'
    | '/_authenticated/perfis'
    | '/_authenticated/personagens'
    | '/_authenticated/refugio'
    | '/_authenticated/registro-vivo'
    | '/_authenticated/revisao'
    | '/_authenticated/state'
    | '/api/campaign-continuity'
    | '/api/characters'
    | '/api/chat'
    | '/api/community-chat'
    | '/api/continuity-maps'
    | '/api/gallery'
    | '/api/generate-infografico'
    | '/api/invite'
    | '/api/mesas'
    | '/api/presence'
    | '/api/private-messages'
    | '/api/profile'
    | '/api/refugio'
    | '/api/session-pulse'
    | '/api/transcribe'
    | '/api/tts'
    | '/_authenticated/campanha/$mesaSlug'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/mapa-continuidade/$mapId'
    | '/_authenticated/surface/$surface'
    | '/_authenticated/trilha/$threadId'
    | '/api/admin/app-access'
    | '/api/admin/character-mesas'
    | '/api/admin/invites'
    | '/api/admin/mesa-memberships'
    | '/api/admin/mesa-responsible-master'
    | '/api/admin/mesas'
    | '/api/admin/player-access-status'
    | '/api/admin/recovery-code'
    | '/api/admin/tal-bootstrap'
    | '/api/auth/google-player-onboarding'
    | '/api/auth/recovery-code'
    | '/api/auth/session'
    | '/api/bridge/decifrar-snapshot-local'
    | '/api/bridge/olhar-de-kairos'
    | '/api/channels/telegram'
    | '/api/channels/telegram-dialogue'
    | '/api/chat/campaigns'
    | '/api/chat/mutations'
    | '/api/chat/thread'
    | '/api/continuity-maps/$mapId'
    | '/api/continuity-maps/documents'
    | '/api/gallery/file'
    | '/api/master/bridge'
    | '/api/master/characters'
    | '/api/master/community-chat'
    | '/api/master/live-session'
    | '/api/master/presence'
    | '/api/master/private-messages'
    | '/api/master/state'
    | '/api/profile/avatar'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/vtt/handoff'
    | '/api/vtt/player-phrase'
    | '/_authenticated/chat/'
    | '/_authenticated/personagem/$characterId/ficha'
    | '/api/master/surface/$surface'
    | '/api/internal/vtt/characters/read'
    | '/api/internal/vtt/handoff/consume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteRoute: typeof ConviteRoute
  ApiCampaignContinuityRoute: typeof ApiCampaignContinuityRoute
  ApiCharactersRoute: typeof ApiCharactersRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiCommunityChatRoute: typeof ApiCommunityChatRoute
  ApiContinuityMapsRoute: typeof ApiContinuityMapsRouteWithChildren
  ApiGalleryRoute: typeof ApiGalleryRouteWithChildren
  ApiGenerateInfograficoRoute: typeof ApiGenerateInfograficoRoute
  ApiInviteRoute: typeof ApiInviteRoute
  ApiMesasRoute: typeof ApiMesasRoute
  ApiPresenceRoute: typeof ApiPresenceRoute
  ApiPrivateMessagesRoute: typeof ApiPrivateMessagesRoute
  ApiProfileRoute: typeof ApiProfileRouteWithChildren
  ApiRefugioRoute: typeof ApiRefugioRoute
  ApiSessionPulseRoute: typeof ApiSessionPulseRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiAdminAppAccessRoute: typeof ApiAdminAppAccessRoute
  ApiAdminCharacterMesasRoute: typeof ApiAdminCharacterMesasRoute
  ApiAdminInvitesRoute: typeof ApiAdminInvitesRoute
  ApiAdminMesaMembershipsRoute: typeof ApiAdminMesaMembershipsRoute
  ApiAdminMesaResponsibleMasterRoute: typeof ApiAdminMesaResponsibleMasterRoute
  ApiAdminMesasRoute: typeof ApiAdminMesasRoute
  ApiAdminPlayerAccessStatusRoute: typeof ApiAdminPlayerAccessStatusRoute
  ApiAdminRecoveryCodeRoute: typeof ApiAdminRecoveryCodeRoute
  ApiAdminTalBootstrapRoute: typeof ApiAdminTalBootstrapRoute
  ApiAuthGooglePlayerOnboardingRoute: typeof ApiAuthGooglePlayerOnboardingRoute
  ApiAuthRecoveryCodeRoute: typeof ApiAuthRecoveryCodeRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiBridgeDecifrarSnapshotLocalRoute: typeof ApiBridgeDecifrarSnapshotLocalRoute
  ApiBridgeOlharDeKairosRoute: typeof ApiBridgeOlharDeKairosRoute
  ApiChannelsTelegramRoute: typeof ApiChannelsTelegramRoute
  ApiChannelsTelegramDialogueRoute: typeof ApiChannelsTelegramDialogueRoute
  ApiMasterBridgeRoute: typeof ApiMasterBridgeRoute
  ApiMasterCharactersRoute: typeof ApiMasterCharactersRoute
  ApiMasterCommunityChatRoute: typeof ApiMasterCommunityChatRoute
  ApiMasterLiveSessionRoute: typeof ApiMasterLiveSessionRoute
  ApiMasterPresenceRoute: typeof ApiMasterPresenceRoute
  ApiMasterPrivateMessagesRoute: typeof ApiMasterPrivateMessagesRoute
  ApiMasterStateRoute: typeof ApiMasterStateRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  ApiVttHandoffRoute: typeof ApiVttHandoffRoute
  ApiVttPlayerPhraseRoute: typeof ApiVttPlayerPhraseRoute
  ApiMasterSurfaceSurfaceRoute: typeof ApiMasterSurfaceSurfaceRoute
  ApiInternalVttCharactersReadRoute: typeof ApiInternalVttCharactersReadRoute
  ApiInternalVttHandoffConsumeRoute: typeof ApiInternalVttHandoffConsumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-pulse': {
      id: '/api/session-pulse'
      path: '/api/session-pulse'
      fullPath: '/api/session-pulse'
      preLoaderRoute: typeof ApiSessionPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refugio': {
      id: '/api/refugio'
      path: '/api/refugio'
      fullPath: '/api/refugio'
      preLoaderRoute: typeof ApiRefugioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private-messages': {
      id: '/api/private-messages'
      path: '/api/private-messages'
      fullPath: '/api/private-messages'
      preLoaderRoute: typeof ApiPrivateMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presence': {
      id: '/api/presence'
      path: '/api/presence'
      fullPath: '/api/presence'
      preLoaderRoute: typeof ApiPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesas': {
      id: '/api/mesas'
      path: '/api/mesas'
      fullPath: '/api/mesas'
      preLoaderRoute: typeof ApiMesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite': {
      id: '/api/invite'
      path: '/api/invite'
      fullPath: '/api/invite'
      preLoaderRoute: typeof ApiInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-infografico': {
      id: '/api/generate-infografico'
      path: '/api/generate-infografico'
      fullPath: '/api/generate-infografico'
      preLoaderRoute: typeof ApiGenerateInfograficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery': {
      id: '/api/gallery'
      path: '/api/gallery'
      fullPath: '/api/gallery'
      preLoaderRoute: typeof ApiGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/continuity-maps': {
      id: '/api/continuity-maps'
      path: '/api/continuity-maps'
      fullPath: '/api/continuity-maps'
      preLoaderRoute: typeof ApiContinuityMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-chat': {
      id: '/api/community-chat'
      path: '/api/community-chat'
      fullPath: '/api/community-chat'
      preLoaderRoute: typeof ApiCommunityChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters': {
      id: '/api/characters'
      path: '/api/characters'
      fullPath: '/api/characters'
      preLoaderRoute: typeof ApiCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaign-continuity': {
      id: '/api/campaign-continuity'
      path: '/api/campaign-continuity'
      fullPath: '/api/campaign-continuity'
      preLoaderRoute: typeof ApiCampaignContinuityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/state': {
      id: '/_authenticated/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof AuthenticatedStateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisao': {
      id: '/_authenticated/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof AuthenticatedRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro-vivo': {
      id: '/_authenticated/registro-vivo'
      path: '/registro-vivo'
      fullPath: '/registro-vivo'
      preLoaderRoute: typeof AuthenticatedRegistroVivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refugio': {
      id: '/_authenticated/refugio'
      path: '/refugio'
      fullPath: '/refugio'
      preLoaderRoute: typeof AuthenticatedRefugioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personagens': {
      id: '/_authenticated/personagens'
      path: '/personagens'
      fullPath: '/personagens'
      preLoaderRoute: typeof AuthenticatedPersonagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/microapp': {
      id: '/_authenticated/microapp'
      path: '/microapp'
      fullPath: '/microapp'
      preLoaderRoute: typeof AuthenticatedMicroappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mestre': {
      id: '/_authenticated/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof AuthenticatedMestreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas': {
      id: '/_authenticated/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof AuthenticatedMapasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kallistis-presente': {
      id: '/_authenticated/kallistis-presente'
      path: '/kallistis-presente'
      fullPath: '/kallistis-presente'
      preLoaderRoute: typeof AuthenticatedKallistisPresenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jardim': {
      id: '/_authenticated/jardim'
      path: '/jardim'
      fullPath: '/jardim'
      preLoaderRoute: typeof AuthenticatedJardimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/vtt/player-phrase': {
      id: '/api/vtt/player-phrase'
      path: '/api/vtt/player-phrase'
      fullPath: '/api/vtt/player-phrase'
      preLoaderRoute: typeof ApiVttPlayerPhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vtt/handoff': {
      id: '/api/vtt/handoff'
      path: '/api/vtt/handoff'
      fullPath: '/api/vtt/handoff'
      preLoaderRoute: typeof ApiVttHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/avatar': {
      id: '/api/profile/avatar'
      path: '/avatar'
      fullPath: '/api/profile/avatar'
      preLoaderRoute: typeof ApiProfileAvatarRouteImport
      parentRoute: typeof ApiProfileRoute
    }
    '/api/master/state': {
      id: '/api/master/state'
      path: '/api/master/state'
      fullPath: '/api/master/state'
      preLoaderRoute: typeof ApiMasterStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/private-messages': {
      id: '/api/master/private-messages'
      path: '/api/master/private-messages'
      fullPath: '/api/master/private-messages'
      preLoaderRoute: typeof ApiMasterPrivateMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/presence': {
      id: '/api/master/presence'
      path: '/api/master/presence'
      fullPath: '/api/master/presence'
      preLoaderRoute: typeof ApiMasterPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/live-session': {
      id: '/api/master/live-session'
      path: '/api/master/live-session'
      fullPath: '/api/master/live-session'
      preLoaderRoute: typeof ApiMasterLiveSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/community-chat': {
      id: '/api/master/community-chat'
      path: '/api/master/community-chat'
      fullPath: '/api/master/community-chat'
      preLoaderRoute: typeof ApiMasterCommunityChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/characters': {
      id: '/api/master/characters'
      path: '/api/master/characters'
      fullPath: '/api/master/characters'
      preLoaderRoute: typeof ApiMasterCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/bridge': {
      id: '/api/master/bridge'
      path: '/api/master/bridge'
      fullPath: '/api/master/bridge'
      preLoaderRoute: typeof ApiMasterBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/file': {
      id: '/api/gallery/file'
      path: '/file'
      fullPath: '/api/gallery/file'
      preLoaderRoute: typeof ApiGalleryFileRouteImport
      parentRoute: typeof ApiGalleryRoute
    }
    '/api/continuity-maps/documents': {
      id: '/api/continuity-maps/documents'
      path: '/documents'
      fullPath: '/api/continuity-maps/documents'
      preLoaderRoute: typeof ApiContinuityMapsDocumentsRouteImport
      parentRoute: typeof ApiContinuityMapsRoute
    }
    '/api/continuity-maps/$mapId': {
      id: '/api/continuity-maps/$mapId'
      path: '/$mapId'
      fullPath: '/api/continuity-maps/$mapId'
      preLoaderRoute: typeof ApiContinuityMapsMapIdRouteImport
      parentRoute: typeof ApiContinuityMapsRoute
    }
    '/api/chat/thread': {
      id: '/api/chat/thread'
      path: '/thread'
      fullPath: '/api/chat/thread'
      preLoaderRoute: typeof ApiChatThreadRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/mutations': {
      id: '/api/chat/mutations'
      path: '/mutations'
      fullPath: '/api/chat/mutations'
      preLoaderRoute: typeof ApiChatMutationsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/campaigns': {
      id: '/api/chat/campaigns'
      path: '/campaigns'
      fullPath: '/api/chat/campaigns'
      preLoaderRoute: typeof ApiChatCampaignsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/channels/telegram-dialogue': {
      id: '/api/channels/telegram-dialogue'
      path: '/api/channels/telegram-dialogue'
      fullPath: '/api/channels/telegram-dialogue'
      preLoaderRoute: typeof ApiChannelsTelegramDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/telegram': {
      id: '/api/channels/telegram'
      path: '/api/channels/telegram'
      fullPath: '/api/channels/telegram'
      preLoaderRoute: typeof ApiChannelsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/olhar-de-kairos': {
      id: '/api/bridge/olhar-de-kairos'
      path: '/api/bridge/olhar-de-kairos'
      fullPath: '/api/bridge/olhar-de-kairos'
      preLoaderRoute: typeof ApiBridgeOlharDeKairosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/decifrar-snapshot-local': {
      id: '/api/bridge/decifrar-snapshot-local'
      path: '/api/bridge/decifrar-snapshot-local'
      fullPath: '/api/bridge/decifrar-snapshot-local'
      preLoaderRoute: typeof ApiBridgeDecifrarSnapshotLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery-code': {
      id: '/api/auth/recovery-code'
      path: '/api/auth/recovery-code'
      fullPath: '/api/auth/recovery-code'
      preLoaderRoute: typeof ApiAuthRecoveryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-player-onboarding': {
      id: '/api/auth/google-player-onboarding'
      path: '/api/auth/google-player-onboarding'
      fullPath: '/api/auth/google-player-onboarding'
      preLoaderRoute: typeof ApiAuthGooglePlayerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tal-bootstrap': {
      id: '/api/admin/tal-bootstrap'
      path: '/api/admin/tal-bootstrap'
      fullPath: '/api/admin/tal-bootstrap'
      preLoaderRoute: typeof ApiAdminTalBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/recovery-code': {
      id: '/api/admin/recovery-code'
      path: '/api/admin/recovery-code'
      fullPath: '/api/admin/recovery-code'
      preLoaderRoute: typeof ApiAdminRecoveryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/player-access-status': {
      id: '/api/admin/player-access-status'
      path: '/api/admin/player-access-status'
      fullPath: '/api/admin/player-access-status'
      preLoaderRoute: typeof ApiAdminPlayerAccessStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mesas': {
      id: '/api/admin/mesas'
      path: '/api/admin/mesas'
      fullPath: '/api/admin/mesas'
      preLoaderRoute: typeof ApiAdminMesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mesa-responsible-master': {
      id: '/api/admin/mesa-responsible-master'
      path: '/api/admin/mesa-responsible-master'
      fullPath: '/api/admin/mesa-responsible-master'
      preLoaderRoute: typeof ApiAdminMesaResponsibleMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mesa-memberships': {
      id: '/api/admin/mesa-memberships'
      path: '/api/admin/mesa-memberships'
      fullPath: '/api/admin/mesa-memberships'
      preLoaderRoute: typeof ApiAdminMesaMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invites': {
      id: '/api/admin/invites'
      path: '/api/admin/invites'
      fullPath: '/api/admin/invites'
      preLoaderRoute: typeof ApiAdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/character-mesas': {
      id: '/api/admin/character-mesas'
      path: '/api/admin/character-mesas'
      fullPath: '/api/admin/character-mesas'
      preLoaderRoute: typeof ApiAdminCharacterMesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/app-access': {
      id: '/api/admin/app-access'
      path: '/api/admin/app-access'
      fullPath: '/api/admin/app-access'
      preLoaderRoute: typeof ApiAdminAppAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trilha/$threadId': {
      id: '/_authenticated/trilha/$threadId'
      path: '/trilha/$threadId'
      fullPath: '/trilha/$threadId'
      preLoaderRoute: typeof AuthenticatedTrilhaThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surface/$surface': {
      id: '/_authenticated/surface/$surface'
      path: '/surface/$surface'
      fullPath: '/surface/$surface'
      preLoaderRoute: typeof AuthenticatedSurfaceSurfaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa-continuidade/$mapId': {
      id: '/_authenticated/mapa-continuidade/$mapId'
      path: '/mapa-continuidade/$mapId'
      fullPath: '/mapa-continuidade/$mapId'
      preLoaderRoute: typeof AuthenticatedMapaContinuidadeMapIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanha/$mesaSlug': {
      id: '/_authenticated/campanha/$mesaSlug'
      path: '/campanha/$mesaSlug'
      fullPath: '/campanha/$mesaSlug'
      preLoaderRoute: typeof AuthenticatedCampanhaMesaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/master/surface/$surface': {
      id: '/api/master/surface/$surface'
      path: '/api/master/surface/$surface'
      fullPath: '/api/master/surface/$surface'
      preLoaderRoute: typeof ApiMasterSurfaceSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/personagem/$characterId/ficha': {
      id: '/_authenticated/personagem/$characterId/ficha'
      path: '/personagem/$characterId/ficha'
      fullPath: '/personagem/$characterId/ficha'
      preLoaderRoute: typeof AuthenticatedPersonagemCharacterIdFichaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/vtt/handoff/consume': {
      id: '/api/internal/vtt/handoff/consume'
      path: '/api/internal/vtt/handoff/consume'
      fullPath: '/api/internal/vtt/handoff/consume'
      preLoaderRoute: typeof ApiInternalVttHandoffConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/vtt/characters/read': {
      id: '/api/internal/vtt/characters/read'
      path: '/api/internal/vtt/characters/read'
      fullPath: '/api/internal/vtt/characters/read'
      preLoaderRoute: typeof ApiInternalVttCharactersReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJardimRoute: typeof AuthenticatedJardimRoute
  AuthenticatedKallistisPresenteRoute: typeof AuthenticatedKallistisPresenteRoute
  AuthenticatedMapasRoute: typeof AuthenticatedMapasRoute
  AuthenticatedMestreRoute: typeof AuthenticatedMestreRoute
  AuthenticatedMicroappRoute: typeof AuthenticatedMicroappRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedPersonagensRoute: typeof AuthenticatedPersonagensRoute
  AuthenticatedRefugioRoute: typeof AuthenticatedRefugioRoute
  AuthenticatedRegistroVivoRoute: typeof AuthenticatedRegistroVivoRoute
  AuthenticatedRevisaoRoute: typeof AuthenticatedRevisaoRoute
  AuthenticatedStateRoute: typeof AuthenticatedStateRoute
  AuthenticatedCampanhaMesaSlugRoute: typeof AuthenticatedCampanhaMesaSlugRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedMapaContinuidadeMapIdRoute: typeof AuthenticatedMapaContinuidadeMapIdRoute
  AuthenticatedSurfaceSurfaceRoute: typeof AuthenticatedSurfaceSurfaceRoute
  AuthenticatedTrilhaThreadIdRoute: typeof AuthenticatedTrilhaThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedPersonagemCharacterIdFichaRoute: typeof AuthenticatedPersonagemCharacterIdFichaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJardimRoute: AuthenticatedJardimRoute,
  AuthenticatedKallistisPresenteRoute: AuthenticatedKallistisPresenteRoute,
  AuthenticatedMapasRoute: AuthenticatedMapasRoute,
  AuthenticatedMestreRoute: AuthenticatedMestreRoute,
  AuthenticatedMicroappRoute: AuthenticatedMicroappRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedPersonagensRoute: AuthenticatedPersonagensRoute,
  AuthenticatedRefugioRoute: AuthenticatedRefugioRoute,
  AuthenticatedRegistroVivoRoute: AuthenticatedRegistroVivoRoute,
  AuthenticatedRevisaoRoute: AuthenticatedRevisaoRoute,
  AuthenticatedStateRoute: AuthenticatedStateRoute,
  AuthenticatedCampanhaMesaSlugRoute: AuthenticatedCampanhaMesaSlugRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedMapaContinuidadeMapIdRoute:
    AuthenticatedMapaContinuidadeMapIdRoute,
  AuthenticatedSurfaceSurfaceRoute: AuthenticatedSurfaceSurfaceRoute,
  AuthenticatedTrilhaThreadIdRoute: AuthenticatedTrilhaThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedPersonagemCharacterIdFichaRoute:
    AuthenticatedPersonagemCharacterIdFichaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiChatRouteChildren {
  ApiChatCampaignsRoute: typeof ApiChatCampaignsRoute
  ApiChatMutationsRoute: typeof ApiChatMutationsRoute
  ApiChatThreadRoute: typeof ApiChatThreadRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatCampaignsRoute: ApiChatCampaignsRoute,
  ApiChatMutationsRoute: ApiChatMutationsRoute,
  ApiChatThreadRoute: ApiChatThreadRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiContinuityMapsRouteChildren {
  ApiContinuityMapsMapIdRoute: typeof ApiContinuityMapsMapIdRoute
  ApiContinuityMapsDocumentsRoute: typeof ApiContinuityMapsDocumentsRoute
}

const ApiContinuityMapsRouteChildren: ApiContinuityMapsRouteChildren = {
  ApiContinuityMapsMapIdRoute: ApiContinuityMapsMapIdRoute,
  ApiContinuityMapsDocumentsRoute: ApiContinuityMapsDocumentsRoute,
}

const ApiContinuityMapsRouteWithChildren =
  ApiContinuityMapsRoute._addFileChildren(ApiContinuityMapsRouteChildren)

interface ApiGalleryRouteChildren {
  ApiGalleryFileRoute: typeof ApiGalleryFileRoute
}

const ApiGalleryRouteChildren: ApiGalleryRouteChildren = {
  ApiGalleryFileRoute: ApiGalleryFileRoute,
}

const ApiGalleryRouteWithChildren = ApiGalleryRoute._addFileChildren(
  ApiGalleryRouteChildren,
)

interface ApiProfileRouteChildren {
  ApiProfileAvatarRoute: typeof ApiProfileAvatarRoute
}

const ApiProfileRouteChildren: ApiProfileRouteChildren = {
  ApiProfileAvatarRoute: ApiProfileAvatarRoute,
}

const ApiProfileRouteWithChildren = ApiProfileRoute._addFileChildren(
  ApiProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteRoute: ConviteRoute,
  ApiCampaignContinuityRoute: ApiCampaignContinuityRoute,
  ApiCharactersRoute: ApiCharactersRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiCommunityChatRoute: ApiCommunityChatRoute,
  ApiContinuityMapsRoute: ApiContinuityMapsRouteWithChildren,
  ApiGalleryRoute: ApiGalleryRouteWithChildren,
  ApiGenerateInfograficoRoute: ApiGenerateInfograficoRoute,
  ApiInviteRoute: ApiInviteRoute,
  ApiMesasRoute: ApiMesasRoute,
  ApiPresenceRoute: ApiPresenceRoute,
  ApiPrivateMessagesRoute: ApiPrivateMessagesRoute,
  ApiProfileRoute: ApiProfileRouteWithChildren,
  ApiRefugioRoute: ApiRefugioRoute,
  ApiSessionPulseRoute: ApiSessionPulseRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiAdminAppAccessRoute: ApiAdminAppAccessRoute,
  ApiAdminCharacterMesasRoute: ApiAdminCharacterMesasRoute,
  ApiAdminInvitesRoute: ApiAdminInvitesRoute,
  ApiAdminMesaMembershipsRoute: ApiAdminMesaMembershipsRoute,
  ApiAdminMesaResponsibleMasterRoute: ApiAdminMesaResponsibleMasterRoute,
  ApiAdminMesasRoute: ApiAdminMesasRoute,
  ApiAdminPlayerAccessStatusRoute: ApiAdminPlayerAccessStatusRoute,
  ApiAdminRecoveryCodeRoute: ApiAdminRecoveryCodeRoute,
  ApiAdminTalBootstrapRoute: ApiAdminTalBootstrapRoute,
  ApiAuthGooglePlayerOnboardingRoute: ApiAuthGooglePlayerOnboardingRoute,
  ApiAuthRecoveryCodeRoute: ApiAuthRecoveryCodeRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiBridgeDecifrarSnapshotLocalRoute: ApiBridgeDecifrarSnapshotLocalRoute,
  ApiBridgeOlharDeKairosRoute: ApiBridgeOlharDeKairosRoute,
  ApiChannelsTelegramRoute: ApiChannelsTelegramRoute,
  ApiChannelsTelegramDialogueRoute: ApiChannelsTelegramDialogueRoute,
  ApiMasterBridgeRoute: ApiMasterBridgeRoute,
  ApiMasterCharactersRoute: ApiMasterCharactersRoute,
  ApiMasterCommunityChatRoute: ApiMasterCommunityChatRoute,
  ApiMasterLiveSessionRoute: ApiMasterLiveSessionRoute,
  ApiMasterPresenceRoute: ApiMasterPresenceRoute,
  ApiMasterPrivateMessagesRoute: ApiMasterPrivateMessagesRoute,
  ApiMasterStateRoute: ApiMasterStateRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  ApiVttHandoffRoute: ApiVttHandoffRoute,
  ApiVttPlayerPhraseRoute: ApiVttPlayerPhraseRoute,
  ApiMasterSurfaceSurfaceRoute: ApiMasterSurfaceSurfaceRoute,
  ApiInternalVttCharactersReadRoute: ApiInternalVttCharactersReadRoute,
  ApiInternalVttHandoffConsumeRoute: ApiInternalVttHandoffConsumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
