/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversaIndexRouteImport } from './routes/conversa.index'
import { Route as ConversaThreadIdRouteImport } from './routes/conversa.$threadId'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as AuthenticatedMestreRouteImport } from './routes/_authenticated/mestre'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiMasterCharactersRouteImport } from './routes/api/master/characters'
import { Route as ApiGerusaThreadRouteImport } from './routes/api/gerusa.thread'
import { Route as ApiGerusaPedagogyRouteImport } from './routes/api/gerusa.pedagogy'
import { Route as ApiGerusaChatRouteImport } from './routes/api/gerusa.chat'
import { Route as ApiGerusaActionRouteImport } from './routes/api/gerusa.action'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaIndexRoute = ConversaIndexRouteImport.update({
  id: '/conversa/',
  path: '/conversa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaThreadIdRoute = ConversaThreadIdRouteImport.update({
  id: '/conversa/$threadId',
  path: '/conversa/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMestreRoute = AuthenticatedMestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMasterCharactersRoute = ApiMasterCharactersRouteImport.update({
  id: '/api/master/characters',
  path: '/api/master/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGerusaThreadRoute = ApiGerusaThreadRouteImport.update({
  id: '/api/gerusa/thread',
  path: '/api/gerusa/thread',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGerusaPedagogyRoute = ApiGerusaPedagogyRouteImport.update({
  id: '/api/gerusa/pedagogy',
  path: '/api/gerusa/pedagogy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGerusaChatRoute = ApiGerusaChatRouteImport.update({
  id: '/api/gerusa/chat',
  path: '/api/gerusa/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGerusaActionRoute = ApiGerusaActionRouteImport.update({
  id: '/api/gerusa/action',
  path: '/api/gerusa/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/api/profile': typeof ApiProfileRoute
  '/conversa/$threadId': typeof ConversaThreadIdRoute
  '/conversa/': typeof ConversaIndexRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/gerusa/action': typeof ApiGerusaActionRoute
  '/api/gerusa/chat': typeof ApiGerusaChatRoute
  '/api/gerusa/pedagogy': typeof ApiGerusaPedagogyRoute
  '/api/gerusa/thread': typeof ApiGerusaThreadRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mestre': typeof AuthenticatedMestreRoute
  '/api/profile': typeof ApiProfileRoute
  '/conversa/$threadId': typeof ConversaThreadIdRoute
  '/conversa': typeof ConversaIndexRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/gerusa/action': typeof ApiGerusaActionRoute
  '/api/gerusa/chat': typeof ApiGerusaChatRoute
  '/api/gerusa/pedagogy': typeof ApiGerusaPedagogyRoute
  '/api/gerusa/thread': typeof ApiGerusaThreadRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mestre': typeof AuthenticatedMestreRoute
  '/api/profile': typeof ApiProfileRoute
  '/conversa/$threadId': typeof ConversaThreadIdRoute
  '/conversa/': typeof ConversaIndexRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/gerusa/action': typeof ApiGerusaActionRoute
  '/api/gerusa/chat': typeof ApiGerusaChatRoute
  '/api/gerusa/pedagogy': typeof ApiGerusaPedagogyRoute
  '/api/gerusa/thread': typeof ApiGerusaThreadRoute
  '/api/master/characters': typeof ApiMasterCharactersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/mestre'
    | '/api/profile'
    | '/conversa/$threadId'
    | '/conversa/'
    | '/api/auth/session'
    | '/api/gerusa/action'
    | '/api/gerusa/chat'
    | '/api/gerusa/pedagogy'
    | '/api/gerusa/thread'
    | '/api/master/characters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/mestre'
    | '/api/profile'
    | '/conversa/$threadId'
    | '/conversa'
    | '/api/auth/session'
    | '/api/gerusa/action'
    | '/api/gerusa/chat'
    | '/api/gerusa/pedagogy'
    | '/api/gerusa/thread'
    | '/api/master/characters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/mestre'
    | '/api/profile'
    | '/conversa/$threadId'
    | '/conversa/'
    | '/api/auth/session'
    | '/api/gerusa/action'
    | '/api/gerusa/chat'
    | '/api/gerusa/pedagogy'
    | '/api/gerusa/thread'
    | '/api/master/characters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ConversaThreadIdRoute: typeof ConversaThreadIdRoute
  ConversaIndexRoute: typeof ConversaIndexRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiGerusaActionRoute: typeof ApiGerusaActionRoute
  ApiGerusaChatRoute: typeof ApiGerusaChatRoute
  ApiGerusaPedagogyRoute: typeof ApiGerusaPedagogyRoute
  ApiGerusaThreadRoute: typeof ApiGerusaThreadRoute
  ApiMasterCharactersRoute: typeof ApiMasterCharactersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa/': {
      id: '/conversa/'
      path: '/conversa'
      fullPath: '/conversa/'
      preLoaderRoute: typeof ConversaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa/$threadId': {
      id: '/conversa/$threadId'
      path: '/conversa/$threadId'
      fullPath: '/conversa/$threadId'
      preLoaderRoute: typeof ConversaThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mestre': {
      id: '/_authenticated/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof AuthenticatedMestreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/master/characters': {
      id: '/api/master/characters'
      path: '/api/master/characters'
      fullPath: '/api/master/characters'
      preLoaderRoute: typeof ApiMasterCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gerusa/thread': {
      id: '/api/gerusa/thread'
      path: '/api/gerusa/thread'
      fullPath: '/api/gerusa/thread'
      preLoaderRoute: typeof ApiGerusaThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gerusa/pedagogy': {
      id: '/api/gerusa/pedagogy'
      path: '/api/gerusa/pedagogy'
      fullPath: '/api/gerusa/pedagogy'
      preLoaderRoute: typeof ApiGerusaPedagogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gerusa/chat': {
      id: '/api/gerusa/chat'
      path: '/api/gerusa/chat'
      fullPath: '/api/gerusa/chat'
      preLoaderRoute: typeof ApiGerusaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gerusa/action': {
      id: '/api/gerusa/action'
      path: '/api/gerusa/action'
      fullPath: '/api/gerusa/action'
      preLoaderRoute: typeof ApiGerusaActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMestreRoute: typeof AuthenticatedMestreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMestreRoute: AuthenticatedMestreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiProfileRoute: ApiProfileRoute,
  ConversaThreadIdRoute: ConversaThreadIdRoute,
  ConversaIndexRoute: ConversaIndexRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiGerusaActionRoute: ApiGerusaActionRoute,
  ApiGerusaChatRoute: ApiGerusaChatRoute,
  ApiGerusaPedagogyRoute: ApiGerusaPedagogyRoute,
  ApiGerusaThreadRoute: ApiGerusaThreadRoute,
  ApiMasterCharactersRoute: ApiMasterCharactersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
